#!/bin/bash

# Shutdown if all transmission downloads are done
# and  if special torrent started


# Special torrent name
spectorrent="shutdown_after_complete"
# auth if needed
auth="" #"--auth username:password"
#-----------------------------------------------------
torrentlist="transmission-remote --list "$auth

count=$($torrentlist | cut -c25-31 | sed -e '/^Done/ d; /^Unknown/ d; 1d; $d')
if [ -z "$count" ]; then
    echo "No active downloads"
    # Special torrent status
    specstat="$($torrentlist | grep $spectorrent | cut -c58-64)"
    if [ ! -z $specstat ] && [ $specstat != "Stopped" ]; then
	echo "Shutdown now"
	# Stop special torrent
	specid="$($torrentlist | grep $spectorrent | cut -c1-4)"
	transmission-remote $auth -t $specid --stop
	transmission-remote $auth --exit
	sudo shutdown -h now
     else
	echo "No shutdown command"
    fi
fi